
# Site settings

url: "http://eemergeit.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

#baseurl: /personal-jekyll-theme

# Google tracking id to track your visitors

google-tracking-id: "UA-70296967-2"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

# Sections shown in the index page

pages_list:
  #About: 'about'
  #Blog: 'latest-post'
  Timeline: 'timeline'
  #Team: 'team'
  Contact: 'contact'

#############
# HTML Head #
#############

author: "eemergeit"
lang: "en"
title: "Coming Soon!"
favicon: "/img/favicon.ico"
description: "eemerge's website"
keywords: "eemerge, 3d, print, 3d models"

################
# Intro layout #
################

black-favicon: "/img/white-3d.png"
background-img: "../img/intro-bg.jpg"
me-img: "/img/startupexagon.jpg"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "Beauty is in the eye of the bemakers"
  - text: "What do you want to print today?"

########
# Blog #
########

post-preview-words: 96

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
google-plus-share: True
linkedin-share: True
pinterest-share: True
vkontakte-share: True
disqus-shortname: "panossakkos"

###############
# Life Events #
###############

events:
  - image: "/img/career/spidertocat.png"
    date: "Nov 2015"
    description: "Concept"
  - image: "/img/career/baracktocat.jpg"
    date: "Jan 2016"
    description: "Prototype"
  - image: "/img/career/spidertocat.png"
    date: "? 2016"
    description: "Release"

# First image of the Career timeline
career-img: "/img/career/default.png"

##################
# Contact layout #
##################

email: "startup@eemerge.it"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/eemergeit/"
  - title: "twitter"
    url: "https://twitter.com/eemergeit"
  #- title: "github"
  #  url: "https://github.com/PanosSakkos/personal-jekyll-theme"
  #- title: "bitcoin"
  #  url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  #- title: "rss"
  #  url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Exclusion list from the generated _site

exclude: ["LICENSE", "README", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems: [jekyll-paginate]
